name: CI Instructions

on:
  [commit, pull]:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Install npm
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Run tests
        run: npm run test