name: CI Instructions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Install npm
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Run tests
        run: npm run test