name: CI Instructions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Use nodeJS
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install npm
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Run tests
        run: npm run test